### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by jiuxuanzhi** [Evertt/swift-webframework#1]
I like this project very much,  'Request' and 'Response' can be replaced with Struct will be more better.

**Comment by Evertt** [comment]
Thank you for checking out my project and giving me feedback, I really appreciate it!
Can you explain to me why that would be better you think?

I know using reference types (like classes) instead of value types (like structs) can cause unwanted side-effects. But in this case I'm using those side-effects to my advantage. The fact that they are classes makes it possible to have this syntax:

``` swift
let handler = {
    request, response, next in

    /// blabla do stuff here

    try next(request, response)

    /// blabla do stuff here
}
```

If I would turn them into structs then I would need to change the syntax to this:

``` swift
let handler = {
    (var request, var response, next) in

    /// blabla do stuff here

    (request, response) = try next(request, response)

    /// blabla do stuff here

    return (request, response)
}
```

I'm willing to do that, if you can tell me the advantage of doing it like that. :-)

**Comment by Evertt** [comment]
Okay I implemented it, the result is visible [at the tryout branch](https://github.com/Evertt/swift-webframework/tree/tryout). Still I would like to know why you think it's better. So far to me it seems it just added extra code.

**Comment by Evertt** [comment]
Oops, I didn't do it even though I said I did. Now I really did implement it though. And to me, it doesn't look like it gives me extra safety, or power, or ease. It only takes me more code actually.

And really I believe it's okay if request and response are classes. Since during any http request cycle, there **is** only _one_ request and _one_ response.
